# Generated by Django 4.2.7 on 2023-11-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_paymenttype_alter_lesson_course_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_lesson', to='courses.lesson', verbose_name='оплаченный Урок'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_course', to='courses.course', verbose_name='оплаченный курс'),
        ),
    ]
